on:
  pull_request:
  repository_dispatch:
    types: [acctest-command]

name: Integration tests

jobs:
  integration-fork:
    runs-on: ubuntu-latest
    if:
      github.event_name == 'repository_dispatch' &&
      github.event.client_payload.slash_command.sha != '' &&
      github.event.client_payload.slash_command.pkg != '' &&
      contains(github.event.client_payload.pull_request.head.sha, github.event.client_payload.slash_command.sha)
    steps:
      - uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8
        with:
          go-version: '1.18'
      - uses: actions-ecosystem/action-regex-match@v2
        id: validate-pkg
        with:
          text: ${{ github.event.client_payload.slash_command.pkg }}
          regex: '[^a-z0-9.\/]'
          flags: gi
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: 'refs/pull/${{ github.event.client_payload.pull_request.number }}/merge'
      - run: make PKG_NAME="${{ github.event.client_payload.slash_command.pkg }}" testacc
        if: ${{ steps.validate-pkg.outputs.match == '' }}
        env:
          LINODE_TOKEN: ${{ secrets.DX_LINODE_TOKEN }}
